/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

export default {
  JavaSidebars: {
    'Java': [
      {
        type: 'autogenerated',
        dirName: 'java/collection', // Generate sidebar slice from docs/tutorials/advanced
      }
    ],
    'Grpc': [
       {
         type: 'autogenerated',
         dirName: 'java/grpc', // Generate sidebar slice from docs/tutorials/advanced
       }
    ]
  },
  MysqlSidebars: {
    'Mysql': [
      {
        type: 'autogenerated',
        dirName: 'mysql', // Generate sidebar slice from docs/tutorials/advanced
      }
    ],
  }
};
